In [22]:
import numpy as np
import pandas as pd

In [23]:
df_batsman_details_1 = pd.read_csv('batsman_details.csv')
df_batsman_details_2 = pd.read_csv('batsman_details_2.csv')
len(df_batsman_details_2)

C:\Users\Hitesh Mohite\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (4,8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

12096

In [24]:
df_batsman_details_1[len(df_batsman_details_1) - 1:]

,Unnamed: 0,batsman,runs,mins,bf,4s,6s,SR,inns,Venue,Date
76299,76299,HDPK Dharmasena (SL),DNB,-,-,-,-,-,2,Colombo (RPS),21-Jun-98

In [38]:
#df_batsman_details_2['Unnamed: 0'] = range(76300, 88297)
#type(df_batsman_details_2['Unnamed: 0'])

pandas.core.series.Series

In [19]:
frames = [df_batsman_details_1, df_batsman_details_2[100:]]
df_batsman_details = pd.concat(frames)
#df_batsman_details = df_batsman_details_1 + df_batsman_details_2[100:]

In [27]:
df_batsman_details
list_of_cols = df_batsman_details.columns.tolist()
list_of_cols = list_of_cols[1 : ] 
list_of_cols
df_batsman_details = df_batsman_details[list_of_cols]
df_batsman_details

,batsman,runs,mins,bf,4s,6s,SR,inns,Venue,Date
0,RG Sharma (INDIA),264,225,173,33,9,152.6,1,Kolkata,13-Nov-14
1,MJ Guptill (NZ),237*,223,163,24,11,145.39,1,Wellington,21-Mar-15
2,V Sehwag (INDIA),219,208,149,25,7,146.97,1,Indore,08-Dec-11
3,CH Gayle (WI),215,212,147,10,16,146.25,1,Canberra,24-Feb-15
4,RG Sharma (INDIA),209,222,158,12,16,132.27,1,Bengaluru,02-Nov-13
5,RG Sharma (INDIA),208*,212,153,13,12,135.94,1,Mohali,13-Dec-17
6,SR Tendulkar (INDIA),200*,226,147,25,3,136.05,1,Gwalior,24-Feb-10
7,CK Coventry (ZIM),194*,191,156,16,7,124.35,1,Bulawayo,16-Aug-09
8,Saeed Anwar (PAK),194,206,146,22,5,132.87,1,Chennai,21-May-97
9,IVA Richards (WI),189*,-,170,21,5,111.17,1,Manchester,31-May-84
10,MJ Guptill (NZ),189*,216,155,19,2,121.93,1,Southampton,02-Jun-13
11,ST Jayasuriya (SL),189,-,161,21,4,117.39,1,Sharjah,29-Oct-00
12,G Kirsten (SA),188*,210,159,13,4,118.23,1,Rawalpindi,16-Feb-96
13,SR Tendulkar (INDIA),186*,221,150,20,3,124,1,Hyderabad (Deccan),08-Nov-99
14,SR Watson (AUS),185*,113,96,15,15,192.7,2,Dhaka,11-Apr-11
15,F du Plessis (SA),185,212,141,16,3,131.2,1,Cape Town,07-Feb-17
16,MS Dhoni (INDIA),183*,210,145,15,10,126.2,2,Jaipur,31-Oct-05
17,SC Ganguly (INDIA),183,210,158,17,7,115.82,1,Taunton,26-May-99
18,V Kohli (INDIA),183,211,148,22,1,123.64,2,Dhaka,18-Mar-12
19,ML Hayden (AUS),181*,227,166,11,10,109.03,1,Hamilton,20-Feb-07
20,LRPL Taylor (NZ),181*,213,147,17,6,123.12,2,Dunedin,07-Mar-18
21,IVA Richards (WI),181,-,125,16,7,144.8,1,Karachi,13-Oct-87
22,MJ Guptill (NZ),180*,198,138,15,11,130.43,2,Hamilton,01-Mar-17
23,JJ Roy (ENG),180,151,151,16,5,119.2,2,Melbourne,14-Jan-18
24,DA Warner (AUS),179,186,128,19,5,139.84,1,Adelaide,26-Jan-17
25,H Masakadza (ZIM),178*,201,167,17,4,106.58,1,Harare,18-Oct-09
26,DA Warner (AUS),178,164,133,19,5,133.83,1,Perth,04-Mar-15
27,Q de Kock (SA),178,142,113,16,11,157.52,2,Centurion,30-Sep-16
28,PR Stirling (IRE),177,177,134,21,5,132.08,1,Toronto,07-Sep-10
29,E Lewis (WI),176*,-,130,17,7,135.38,1,The Oval,27-Sep-17
...,...,...,...,...,...,...,...,...,...,...
12066,CB Sole (SCOT),DNB,-,-,-,-,-,1,Bulawayo,15 Mar 2018
12067,BTJ Wheal (SCOT),DNB,-,-,-,-,-,1,Bulawayo,15 Mar 2018
12068,TJ Murtagh (IRE),DNB,-,-,-,-,-,1,Harare,18 Mar 2018
12069,KAJ Roach (WI),DNB,-,-,-,-,-,2,Harare,19 Mar 2018
12070,D Bishoo (WI),DNB,-,-,-,-,-,2,Harare,19 Mar 2018
12071,KMA Paul (WI),DNB,-,-,-,-,-,2,Harare,19 Mar 2018
12072,Dawlat Zadran (AFG),DNB,-,-,-,-,-,2,Harare,20 Mar 2018
12073,Sharafuddin Ashraf (AFG),DNB,-,-,-,-,-,2,Harare,20 Mar 2018
12074,Rashid Khan (AFG),DNB,-,-,-,-,-,2,Harare,20 Mar 2018
12075,Mujeeb Ur Rahman (AFG),DNB,-,-,-,-,-,2,Harare,20 Mar 2018
12076,AC Evans (SCOT),DNB,-,-,-,-,-,2,Harare,21 Mar 2018
12077,SM Sharif (SCOT),DNB,-,-,-,-,-,2,Harare,21 Mar 2018
12078,TB Sole (SCOT),DNB,-,-,-,-,-,2,Harare,21 Mar 2018
12079,BTJ Wheal (SCOT),DNB,-,-,-,-,-,2,Harare,21 Mar 2018
12080,Qadeer Ahmed (UAE),DNB,-,-,-,-,-,1,Harare,22 Mar 2018
12081,Amir Hayat (UAE),DNB,-,-,-,-,-,1,Harare,22 Mar 2018
12082,TL Chatara (ZIM),DNB,-,-,-,-,-,2,Harare,22 Mar 2018
12083,B Muzarabani (ZIM),DNB,-,-,-,-,-,2,Harare,22 Mar 2018
12084,TJ Murtagh (IRE),DNB,-,-,-,-,-,1,Harare,23 Mar 2018
12085,WB Rankin (IRE),DNB,-,-,-,-,-,1,Harare,23 Mar 2018
12086,Dawlat Zadran (AFG),DNB,-,-,-,-,-,2,Harare,23 Mar 2018
12087,Sharafuddin Ashraf (AFG),DNB,-,-,-,-,-,2,Harare,23 Mar 2018
12088,Rashid Khan (AFG),DNB,-,-,-,-,-,2,Harare,23 Mar 2018
12089,Mujeeb Ur Rahman (AFG),DNB,-,-,-,-,-,2,Harare,23 Mar 2018
12090,Asghar Stanikzai (AFG),DNB,-,-,-,-,-,2,Harare,25 Mar 2018
12091,Dawlat Zadran (AFG),DNB,-,-,-,-,-,2,Harare,25 Mar 2018
12092,Najibullah Zadran (AFG),DNB,-,-,-,-,-,2,Harare,25 Mar 2018
12093,Sharafuddin Ashraf (AFG),DNB,-,-,-,-,-,2,Harare,25 Mar 2018
12094,Rashid Khan (AFG),DNB,-,-,-,-,-,2,Harare,25 Mar 2018
12095,Mujeeb Ur Rahman (AFG),DNB,-,-,-,-,-,2,Harare,25 Mar 2018

In [43]:
df_batsman_details['#'] = range(0, len(df_batsman_details))
list_of_cols = df_batsman_details.columns.tolist()
list_of_cols = list_of_cols[-1 : ] + list_of_cols[ : -1] 
df_batsman_details = df_batsman_details[list_of_cols]
df_batsman_details

,#,batsman,runs,mins,bf,4s,6s,SR,inns,Venue,Date
0,0,RG Sharma (INDIA),264,225,173,33,9,152.6,1,Kolkata,13-Nov-14
1,1,MJ Guptill (NZ),237*,223,163,24,11,145.39,1,Wellington,21-Mar-15
2,2,V Sehwag (INDIA),219,208,149,25,7,146.97,1,Indore,08-Dec-11
3,3,CH Gayle (WI),215,212,147,10,16,146.25,1,Canberra,24-Feb-15
4,4,RG Sharma (INDIA),209,222,158,12,16,132.27,1,Bengaluru,02-Nov-13
5,5,RG Sharma (INDIA),208*,212,153,13,12,135.94,1,Mohali,13-Dec-17
6,6,SR Tendulkar (INDIA),200*,226,147,25,3,136.05,1,Gwalior,24-Feb-10
7,7,CK Coventry (ZIM),194*,191,156,16,7,124.35,1,Bulawayo,16-Aug-09
8,8,Saeed Anwar (PAK),194,206,146,22,5,132.87,1,Chennai,21-May-97
9,9,IVA Richards (WI),189*,-,170,21,5,111.17,1,Manchester,31-May-84
10,10,MJ Guptill (NZ),189*,216,155,19,2,121.93,1,Southampton,02-Jun-13
11,11,ST Jayasuriya (SL),189,-,161,21,4,117.39,1,Sharjah,29-Oct-00
12,12,G Kirsten (SA),188*,210,159,13,4,118.23,1,Rawalpindi,16-Feb-96
13,13,SR Tendulkar (INDIA),186*,221,150,20,3,124,1,Hyderabad (Deccan),08-Nov-99
14,14,SR Watson (AUS),185*,113,96,15,15,192.7,2,Dhaka,11-Apr-11
15,15,F du Plessis (SA),185,212,141,16,3,131.2,1,Cape Town,07-Feb-17
16,16,MS Dhoni (INDIA),183*,210,145,15,10,126.2,2,Jaipur,31-Oct-05
17,17,SC Ganguly (INDIA),183,210,158,17,7,115.82,1,Taunton,26-May-99
18,18,V Kohli (INDIA),183,211,148,22,1,123.64,2,Dhaka,18-Mar-12
19,19,ML Hayden (AUS),181*,227,166,11,10,109.03,1,Hamilton,20-Feb-07
20,20,LRPL Taylor (NZ),181*,213,147,17,6,123.12,2,Dunedin,07-Mar-18
21,21,IVA Richards (WI),181,-,125,16,7,144.8,1,Karachi,13-Oct-87
22,22,MJ Guptill (NZ),180*,198,138,15,11,130.43,2,Hamilton,01-Mar-17
23,23,JJ Roy (ENG),180,151,151,16,5,119.2,2,Melbourne,14-Jan-18
24,24,DA Warner (AUS),179,186,128,19,5,139.84,1,Adelaide,26-Jan-17
25,25,H Masakadza (ZIM),178*,201,167,17,4,106.58,1,Harare,18-Oct-09
26,26,DA Warner (AUS),178,164,133,19,5,133.83,1,Perth,04-Mar-15
27,27,Q de Kock (SA),178,142,113,16,11,157.52,2,Centurion,30-Sep-16
28,28,PR Stirling (IRE),177,177,134,21,5,132.08,1,Toronto,07-Sep-10
29,29,E Lewis (WI),176*,-,130,17,7,135.38,1,The Oval,27-Sep-17
...,...,...,...,...,...,...,...,...,...,...,...
12066,88266,CB Sole (SCOT),DNB,-,-,-,-,-,1,Bulawayo,15 Mar 2018
12067,88267,BTJ Wheal (SCOT),DNB,-,-,-,-,-,1,Bulawayo,15 Mar 2018
12068,88268,TJ Murtagh (IRE),DNB,-,-,-,-,-,1,Harare,18 Mar 2018
12069,88269,KAJ Roach (WI),DNB,-,-,-,-,-,2,Harare,19 Mar 2018
12070,88270,D Bishoo (WI),DNB,-,-,-,-,-,2,Harare,19 Mar 2018
12071,88271,KMA Paul (WI),DNB,-,-,-,-,-,2,Harare,19 Mar 2018
12072,88272,Dawlat Zadran (AFG),DNB,-,-,-,-,-,2,Harare,20 Mar 2018
12073,88273,Sharafuddin Ashraf (AFG),DNB,-,-,-,-,-,2,Harare,20 Mar 2018
12074,88274,Rashid Khan (AFG),DNB,-,-,-,-,-,2,Harare,20 Mar 2018
12075,88275,Mujeeb Ur Rahman (AFG),DNB,-,-,-,-,-,2,Harare,20 Mar 2018
12076,88276,AC Evans (SCOT),DNB,-,-,-,-,-,2,Harare,21 Mar 2018
12077,88277,SM Sharif (SCOT),DNB,-,-,-,-,-,2,Harare,21 Mar 2018
12078,88278,TB Sole (SCOT),DNB,-,-,-,-,-,2,Harare,21 Mar 2018
12079,88279,BTJ Wheal (SCOT),DNB,-,-,-,-,-,2,Harare,21 Mar 2018
12080,88280,Qadeer Ahmed (UAE),DNB,-,-,-,-,-,1,Harare,22 Mar 2018
12081,88281,Amir Hayat (UAE),DNB,-,-,-,-,-,1,Harare,22 Mar 2018
12082,88282,TL Chatara (ZIM),DNB,-,-,-,-,-,2,Harare,22 Mar 2018
12083,88283,B Muzarabani (ZIM),DNB,-,-,-,-,-,2,Harare,22 Mar 2018
12084,88284,TJ Murtagh (IRE),DNB,-,-,-,-,-,1,Harare,23 Mar 2018
12085,88285,WB Rankin (IRE),DNB,-,-,-,-,-,1,Harare,23 Mar 2018
12086,88286,Dawlat Zadran (AFG),DNB,-,-,-,-,-,2,Harare,23 Mar 2018
12087,88287,Sharafuddin Ashraf (AFG),DNB,-,-,-,-,-,2,Harare,23 Mar 2018
12088,88288,Rashid Khan (AFG),DNB,-,-,-,-,-,2,Harare,23 Mar 2018
12089,88289,Mujeeb Ur Rahman (AFG),DNB,-,-,-,-,-,2,Harare,23 Mar 2018
12090,88290,Asghar Stanikzai (AFG),DNB,-,-,-,-,-,2,Harare,25 Mar 2018
12091,88291,Dawlat Zadran (AFG),DNB,-,-,-,-,-,2,Harare,25 Mar 2018
12092,88292,Najibullah Zadran (AFG),DNB,-,-,-,-,-,2,Harare,25 Mar 2018
12093,88293,Sharafuddin Ashraf (AFG),DNB,-,-,-,-,-,2,Harare,25 Mar 2018
12094,88294,Rashid Khan (AFG),DNB,-,-,-,-,-,2,Harare,25 Mar 2018
12095,88295,Mujeeb Ur Rahman (AFG),DNB,-,-,-,-,-,2,Harare,25 Mar 2018

In [45]:
df_batsman_details.set_index('#', inplace=True)
df_batsman_details

,batsman,runs,mins,bf,4s,6s,SR,inns,Venue,Date
#,,,,,,,,,,
0,RG Sharma (INDIA),264,225,173,33,9,152.6,1,Kolkata,13-Nov-14
1,MJ Guptill (NZ),237*,223,163,24,11,145.39,1,Wellington,21-Mar-15
2,V Sehwag (INDIA),219,208,149,25,7,146.97,1,Indore,08-Dec-11
3,CH Gayle (WI),215,212,147,10,16,146.25,1,Canberra,24-Feb-15
4,RG Sharma (INDIA),209,222,158,12,16,132.27,1,Bengaluru,02-Nov-13
5,RG Sharma (INDIA),208*,212,153,13,12,135.94,1,Mohali,13-Dec-17
6,SR Tendulkar (INDIA),200*,226,147,25,3,136.05,1,Gwalior,24-Feb-10
7,CK Coventry (ZIM),194*,191,156,16,7,124.35,1,Bulawayo,16-Aug-09
8,Saeed Anwar (PAK),194,206,146,22,5,132.87,1,Chennai,21-May-97
9,IVA Richards (WI),189*,-,170,21,5,111.17,1,Manchester,31-May-84
10,MJ Guptill (NZ),189*,216,155,19,2,121.93,1,Southampton,02-Jun-13
11,ST Jayasuriya (SL),189,-,161,21,4,117.39,1,Sharjah,29-Oct-00
12,G Kirsten (SA),188*,210,159,13,4,118.23,1,Rawalpindi,16-Feb-96
13,SR Tendulkar (INDIA),186*,221,150,20,3,124,1,Hyderabad (Deccan),08-Nov-99
14,SR Watson (AUS),185*,113,96,15,15,192.7,2,Dhaka,11-Apr-11
15,F du Plessis (SA),185,212,141,16,3,131.2,1,Cape Town,07-Feb-17
16,MS Dhoni (INDIA),183*,210,145,15,10,126.2,2,Jaipur,31-Oct-05
17,SC Ganguly (INDIA),183,210,158,17,7,115.82,1,Taunton,26-May-99
18,V Kohli (INDIA),183,211,148,22,1,123.64,2,Dhaka,18-Mar-12
19,ML Hayden (AUS),181*,227,166,11,10,109.03,1,Hamilton,20-Feb-07
20,LRPL Taylor (NZ),181*,213,147,17,6,123.12,2,Dunedin,07-Mar-18
21,IVA Richards (WI),181,-,125,16,7,144.8,1,Karachi,13-Oct-87
22,MJ Guptill (NZ),180*,198,138,15,11,130.43,2,Hamilton,01-Mar-17
23,JJ Roy (ENG),180,151,151,16,5,119.2,2,Melbourne,14-Jan-18
24,DA Warner (AUS),179,186,128,19,5,139.84,1,Adelaide,26-Jan-17
25,H Masakadza (ZIM),178*,201,167,17,4,106.58,1,Harare,18-Oct-09
26,DA Warner (AUS),178,164,133,19,5,133.83,1,Perth,04-Mar-15
27,Q de Kock (SA),178,142,113,16,11,157.52,2,Centurion,30-Sep-16
28,PR Stirling (IRE),177,177,134,21,5,132.08,1,Toronto,07-Sep-10
29,E Lewis (WI),176*,-,130,17,7,135.38,1,The Oval,27-Sep-17
...,...,...,...,...,...,...,...,...,...,...
88266,CB Sole (SCOT),DNB,-,-,-,-,-,1,Bulawayo,15 Mar 2018
88267,BTJ Wheal (SCOT),DNB,-,-,-,-,-,1,Bulawayo,15 Mar 2018
88268,TJ Murtagh (IRE),DNB,-,-,-,-,-,1,Harare,18 Mar 2018
88269,KAJ Roach (WI),DNB,-,-,-,-,-,2,Harare,19 Mar 2018
88270,D Bishoo (WI),DNB,-,-,-,-,-,2,Harare,19 Mar 2018
88271,KMA Paul (WI),DNB,-,-,-,-,-,2,Harare,19 Mar 2018
88272,Dawlat Zadran (AFG),DNB,-,-,-,-,-,2,Harare,20 Mar 2018
88273,Sharafuddin Ashraf (AFG),DNB,-,-,-,-,-,2,Harare,20 Mar 2018
88274,Rashid Khan (AFG),DNB,-,-,-,-,-,2,Harare,20 Mar 2018
88275,Mujeeb Ur Rahman (AFG),DNB,-,-,-,-,-,2,Harare,20 Mar 2018
88276,AC Evans (SCOT),DNB,-,-,-,-,-,2,Harare,21 Mar 2018
88277,SM Sharif (SCOT),DNB,-,-,-,-,-,2,Harare,21 Mar 2018
88278,TB Sole (SCOT),DNB,-,-,-,-,-,2,Harare,21 Mar 2018
88279,BTJ Wheal (SCOT),DNB,-,-,-,-,-,2,Harare,21 Mar 2018
88280,Qadeer Ahmed (UAE),DNB,-,-,-,-,-,1,Harare,22 Mar 2018
88281,Amir Hayat (UAE),DNB,-,-,-,-,-,1,Harare,22 Mar 2018
88282,TL Chatara (ZIM),DNB,-,-,-,-,-,2,Harare,22 Mar 2018
88283,B Muzarabani (ZIM),DNB,-,-,-,-,-,2,Harare,22 Mar 2018
88284,TJ Murtagh (IRE),DNB,-,-,-,-,-,1,Harare,23 Mar 2018
88285,WB Rankin (IRE),DNB,-,-,-,-,-,1,Harare,23 Mar 2018
88286,Dawlat Zadran (AFG),DNB,-,-,-,-,-,2,Harare,23 Mar 2018
88287,Sharafuddin Ashraf (AFG),DNB,-,-,-,-,-,2,Harare,23 Mar 2018
88288,Rashid Khan (AFG),DNB,-,-,-,-,-,2,Harare,23 Mar 2018
88289,Mujeeb Ur Rahman (AFG),DNB,-,-,-,-,-,2,Harare,23 Mar 2018
88290,Asghar Stanikzai (AFG),DNB,-,-,-,-,-,2,Harare,25 Mar 2018
88291,Dawlat Zadran (AFG),DNB,-,-,-,-,-,2,Harare,25 Mar 2018
88292,Najibullah Zadran (AFG),DNB,-,-,-,-,-,2,Harare,25 Mar 2018
88293,Sharafuddin Ashraf (AFG),DNB,-,-,-,-,-,2,Harare,25 Mar 2018
88294,Rashid Khan (AFG),DNB,-,-,-,-,-,2,Harare,25 Mar 2018
88295,Mujeeb Ur Rahman (AFG),DNB,-,-,-,-,-,2,Harare,25 Mar 2018

In [47]:
df_batsman_details.to_csv('batsman_details.csv', sep=',')